#!/usr/bin/env bash
# Write one job folder per point of the shock-droplet parameter study.
#
#   ./make-sweep.sh <your-name> [cpu|gpu] [cluster]
#
# Run from the repository root. Each point is a job.yml naming the registered
# case shock_droplet_2d and differing ONLY in args, so every point provably
# ran identical code -- the one thing a parameter study has to guarantee.
#
# Every wall time below was measured on this cluster, not estimated, except
# where marked.
set -euo pipefail

NAME=${1:?usage: make-sweep.sh <your-name> [cpu|gpu] [cluster]}
WHERE=${2:-cpu}
CLUSTER=${3:-xenon}
ROOT="input/$CLUSTER/MFC/$NAME"

write_job() {           # write_job <suffix> <walltime> <args-yaml> [extra-yaml]
  local dir="$ROOT/task3-$1" wall="$2" args="$3" extra="${4:-}"
  mkdir -p "$dir"
  {
    echo "# SCC26 practice task 3 — generated by make-sweep.sh"
    echo "suite: MFC"
    echo "case: shock_droplet_2d"
    echo "args: $args"
    [ -n "$extra" ] && echo "$extra"
    echo "resources:"
    echo "  partition: $PART"
    echo "  nodes: 1"
    echo "  tasks_per_node: $TPN"
    echo "  walltime: \"$wall\""
    echo "build:"
    echo "  gpu: $GPU"
    echo "  toolchain: $TOOLCHAIN"
  } > "$dir/job.yml"
  echo "  $dir/job.yml"
}

if [ "$WHERE" = gpu ]; then
  PART=gpu; TPN=4; GPU=acc; TOOLCHAIN=nvhpc-acc
  echo "writing GPU study for $NAME:"
  # 2400x600 keeps four A100s busy. The pair G1/G2 differ only in
  # run_time_info and are the point of the GPU set: 33 s versus 311 s.
  write_job gpu-baseline      "00:30:00" '["-N", "2400", "--tend", "0.05", "--saves", "4", "--no-run-time-info"]'
  write_job gpu-runtimeinfo   "00:30:00" '["-N", "2400", "--tend", "0.05", "--saves", "4"]'
  write_job gpu-viscous       "00:30:00" '["-N", "2400", "--tend", "0.05", "--saves", "4", "--no-run-time-info", "--viscous"]'
  write_job gpu-surften       "00:30:00" '["-N", "2400", "--tend", "0.05", "--saves", "4", "--no-run-time-info", "--sigma", "0.0728"]'
  # Deliberately far too small for an A100: 8.34 ns/gp/eq/rhs against 0.28.
  write_job gpu-starved       "00:30:00" '["-N", "240", "--tend", "0.25", "--saves", "4"]'
else
  PART=cpu; TPN=4; GPU=none; TOOLCHAIN=gcc-ompi5
  echo "writing CPU study for $NAME:"
  # The baseline is the only point that needs a movie; the rest are
  # measurements, and Silo writes would distort their wall times.
  write_job baseline          "00:30:00" '[]' 'visualize: true
preview: alpha1'
  write_job mach1.2           "00:30:00" '["--mach", "1.2", "--tend", "0.25"]'
  write_job mach2.4           "00:30:00" '["--mach", "2.4", "--tend", "0.25"]'
  write_job mach3.0           "00:30:00" '["--mach", "3.0", "--tend", "0.25"]'
  write_job n120              "00:30:00" '["-N", "120", "--tend", "0.25"]'
  write_job n480              "00:30:00" '["-N", "480", "--tend", "0.25"]'
  # Extrapolated, not measured: ~17 min, hence the longer walltime.
  write_job n960              "00:45:00" '["-N", "960", "--tend", "0.25", "--saves", "20"]'
  write_job viscous           "00:30:00" '["--tend", "0.25", "--viscous"]'
  write_job surften           "00:30:00" '["--tend", "0.25", "--sigma", "0.0728"]'
  write_job viscous-surften   "00:30:00" '["--tend", "0.25", "--viscous", "--sigma", "0.0728"]'
  write_job no-runtimeinfo    "00:30:00" '["--tend", "0.25", "--no-run-time-info"]'
fi

echo
echo "Check them, then: git add $ROOT && git commit && git push"
echo "Read the results with:  python3 suites/MFC/sweep-table.py output/$CLUSTER/MFC/$NAME/task3-*"
