#!/usr/bin/env bash
# Write one job folder per point of a convergence sweep.
#
#   ./make-sweep.sh <your-name> [cluster]
#
# Run from the repository root. Creates
# input/<cluster>/MFC/<your-name>/task2-n<N>-weno<order>/job.yml for each
# combination below, then you commit them all and push once.
set -euo pipefail

NAME=${1:?usage: make-sweep.sh <your-name> [cluster]}
CLUSTER=${2:-xenon}
ROOT="input/$CLUSTER/MFC/$NAME"

# Five resolutions give four order estimates, run in well under a minute each,
# and stay far away from round-off. Three WENO orders show the whole point of
# the exercise: at N=512 the first-order scheme's error is about 5e-03 and the
# fifth-order scheme's is about 4e-10.
RESOLUTIONS="32 64 128 256 512"
ORDERS="1 3 5"

# A fourth series at a much smaller CFL. Without it WENO5 appears to be third
# order -- see the README. Three points is enough to show the difference.
LOWCFL_RESOLUTIONS="32 64 128"

write_job() {
  local dir="$1" n="$2" order="$3" cfl="${4:-}"
  mkdir -p "$dir"
  {
    echo "# SCC26 practice task 2 — generated by make-sweep.sh"
    echo "suite: MFC"
    echo "case: advection_1d"
    if [ -n "$cfl" ]; then
      echo "args: [\"-N\", \"$n\", \"--order\", \"$order\", \"--cfl\", \"$cfl\"]"
    else
      echo "args: [\"-N\", \"$n\", \"--order\", \"$order\"]"
    fi
    echo "resources:"
    echo "  partition: cpu"
    echo "  nodes: 1"
    echo "  tasks_per_node: 1"
    echo "  walltime: \"00:20:00\""
    echo "build:"
    echo "  gpu: none"
    echo "  toolchain: gcc-ompi5"
  } > "$dir/job.yml"
  echo "  $dir/job.yml"
}

echo "writing sweep for $NAME on $CLUSTER:"
for order in $ORDERS; do
  for n in $RESOLUTIONS; do
    write_job "$ROOT/task2-n$n-weno$order" "$n" "$order"
  done
done
for n in $LOWCFL_RESOLUTIONS; do
  write_job "$ROOT/task2-n$n-weno5-cfl0.025" "$n" 5 0.025
done

echo
echo "$(find "$ROOT" -name job.yml -newermt '-1 minute' | wc -l) job(s) written."
echo "Check them, then: git add $ROOT && git commit && git push"
